language: go
go:
  - 1.9.x
  - 1.x
go_import_path: github.com/boantp
before_script:
  - cd /home/travis/gopath/src/github.com/boantp/parking_lot
  - rm -rf *
  - go get -u -v github.com/boantp/parking_lot
  - go run main.go
  - cd parking
script:
 - go test -v ./...
